"""add matching tables

Revision ID: ec84cb14d31c
Revises: b7a1c9d4e2f0
Create Date: 2026-02-20 16:56:46.060588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec84cb14d31c'
down_revision: Union[str, Sequence[str], None] = 'b7a1c9d4e2f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_profile_embeddings_embedding_hnsw', table_name='profile_embeddings', postgresql_using='hnsw')
    op.drop_index('ix_vacancy_embeddings_embedding_hnsw', table_name='vacancy_embeddings', postgresql_using='hnsw')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_vacancy_embeddings_embedding_hnsw', 'vacancy_embeddings', ['embedding'], unique=False, postgresql_using='hnsw')
    op.create_index('ix_profile_embeddings_embedding_hnsw', 'profile_embeddings', ['embedding'], unique=False, postgresql_using='hnsw')
    # ### end Alembic commands ###
