"""Shared lexical markers for vacancy requirement classification."""

SECTION_HEADERS = {
    "requirements": [
        "требования",
        "мы ожидаем",
        "ожидания от кандидата",
        "требования к кандидату",
        "квалификационные требования",
        "необходимые навыки",
        "ключевые навыки",
        "обязательные требования",
        "что важно",
        "важно",
        "профиль кандидата",
        "requirements",
        "we expect",
        "must have",
        "mandatory",
        "required skills",
        "key requirements",
        "what we expect",
    ],
    "nice_to_have": [
        "будет плюсом",
        "плюсом будет",
        "желательно",
        "приветствуется",
        "как преимущество",
        "будет преимуществом",
        "дополнительно",
        "хорошо если",
        "не обязательно",
        "по возможности",
        "nice to have",
        "good to have",
        "would be a plus",
        "preferred",
        "bonus",
        "optional",
        "advantage",
    ],
    "responsibilities": [
        "обязанности",
        "задачи",
        "что предстоит делать",
        "чем заниматься",
        "роль",
        "responsibilities",
        "what you will do",
    ],
    "conditions": [
        "мы предлагаем",
        "условия",
        "компенсация",
        "benefits",
        "we offer",
        "conditions",
    ],
    "other": [
        "о компании",
        "about",
    ],
}

LINE_MARKERS = {
    "must": [
        "обязательно",
        "необходимо",
        "требуется",
        "нужно",
        "строго",
        "обязателен",
        "обязательна",
        "обязательны",
        "только",
        "must",
        "required",
        "mandatory",
        "не менее",
        "strong",
        "proficiency in",
        "solid knowledge of",
    ],
    "nice": [
        "будет плюсом",
        "плюсом будет",
        "желательно",
        "приветствуется",
        "как преимущество",
        "будет преимуществом",
        "будет большим плюсом",
        "будет дополнительным плюсом",
        "хорошо если",
        "не обязательно",
        "по возможности",
        "плюсом",
        "nice to have",
        "good to have",
        "would be a plus",
        "preferred",
        "optional",
        "bonus",
        "advantage",
    ],
}

STARTS_LIKE_REQUIREMENT = [
    "опыт",
    "опыт работы",
    "умение",
    "навыки",
    "знание",
    "понимание",
    "владение",
    "способность",
    "практика",
    "понимание принципов",
    "умение работать с",
]

EXCEPTIONS = {
    "not_relocation_patterns": [
        r"\bпереезд\s+на\s+(go|golang|микросервисы|новую архитектуру|kubernetes)\b",
        r"\b(migration to|moving to)\b",
    ],
    "only_format_patterns": [
        r"\bтолько\s+(офис|в\s+офисе|удал[её]нк[ауы]|remote|office)\b",
    ],
}
